name: headache_tracker
description: 'Headache tracking application'
publish_to: 'none'
version: 0.1.0

environment:
    sdk: ^3.10.1

dependencies:
    collection: ^1.19.1
    flutter:
        sdk: flutter
    flutter_launcher_icons: ^0.14.4
    intl: ^0.20.2
    path: ^1.9.1
    provider: ^6.1.5+1
    sqflite: ^2.4.2
    wakelock_plus: ^1.4.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0

flutter:
    uses-material-design: true

flutter_launcher_icons:
    android: 'launcher_icon'
    ios: true
    image_path: 'assets/images/playstore.png'
    min_sdk_android: 21
